language: python
python:
    - 2.7
    - pypy
    - 3.3
    - 3.4
    - 3.5
    - nightly
#    - pypy3
install: "pip install PySimpleGUI PySimpleGUI27 pytest nuitka"
before_script:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3
script: ./run_tests.sh

