language: python
python:
    - 2.7
    #- pypy
    #- 3.3
    - 3.4
    - 3.5
    - 3.6
    #- nightly
    #- pypy3
matrix:
  include:
    - python: 3.7
      dist: xenial    # required for Python 3.7 (travis-ci/travis-ci#9069)
      sudo: required  # required for Python 3.7 (travis-ci/travis-ci#9069)
    - python: pypy3
      dist: xenial
      sudo: required
install:
    - "sudo apt-get install scons chrpath"
    - "pip install pytest nuitka pycryptodomex"
before_script:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3
script: ./tests/run_tests.sh
