language: python
python:
    - 2.7.8
    - 2.7
    - pypy
    - 3.3
    - 3.4
    - 3.5
    - nightly
#    - pypy3
install: "pip install PySimpleGUI PySimpleGUI27 pytest nuitka"
script: ./run_tests.sh

