language: python
python:
    #- 2.7
    #- pypy
    #- 3.3
    - 3.4
    - 3.5
    - 3.6
    - nightly
    - pypy3
install: "pip install pytest nuitka pycryptodomex"
before_script:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3
script: ./tests/run_tests.sh
